### ISSUE TITLE
Command aliases

### ISSUE THREAD

**Issue by AlexSkrypnyk** [ahoy-cli/ahoy#110]
**Is your feature request related to a problem? Please describe.**
Sometimes, it is required to have commands to have multiple aliases.

**Describe the solution you'd like**
I'd like to have an `alias` or `aliases` field for each command to be able to specify one or more aliases.

**Describe alternatives you've considered**
Create another Ahoy command and call the original one. But this will be creating sub-processes. And also will be shown as a separate command when calling `ahoy`.

**Comment by hanoii** [comment]
I'd also like this.

**Comment by ocean** [comment]
Cool, this sounds like a good idea, thanks for the suggestion and support @AlexSkrypnyk and @hanoii 

I'll have more of a think about this, no short term promises at this stage 😄

**Comment by ocean** [comment]
Shipped! 🚢 

Thanks for the push @AlexSkrypnyk  and @hanoii  🙌 

Small readme update about the aliases here https://github.com/ahoy-cli/ahoy#command-aliases

A documentation update is under way as well.
