### ISSUE TITLE
Make imports optional

### ISSUE THREAD

**Issue by hanoii** [ahoy-cli/ahoy#118]
I would like imports to be defined but that they wouldn't err if the import file doesn't exist or it's empty.

**Comment by ocean** [comment]
Hi @hanoii thanks very much for this! Yes, I'm very happy to get contributions and pull requests from you, that would be great. 

I'm nearing the end of a long a complex website release at the moment, so forgive me if I don't get a good look at this right away, but I do have some time planned soon to do some more things with `ahoy`. 

Are you able to write a test to demonstrate this feature working?
