### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by frankcarey** [ahoy-cli/ahoy#33]
Update the examples based on the ton of goodies we've all been creating:

Nucivic Examples: https://github.com/NuCivic/dkan/tree/7.x-1.x/.ahoy

**Comment by frankcarey** [comment]
These are still out of date, but I did replace the `{{args}}` with `"$@"` so this should be working better.

**Comment by schuhwerk** [comment]
The link you provided is (no longer) working (for me). Didn't find it [their repo](https://github.com/GetDKAN/dkan/search?q=ahoy&type=issues) neither.

**Comment by AlexSkrypnyk** [comment]
Closing as the referred link no longer contains referenced Ahoy config.
