### ISSUE TITLE
hide: true only works for first tier commands

### ISSUE THREAD

**Issue by dkinzer** [ahoy-cli/ahoy#43]
When defining an api it would be useful to be able to hide detail commands for more than just the first tier of the command tree.  If I try to hide say `ahoy docker helper-function` by making `hide: true` in the `helper-function` definition object, It is not hidden when I run `ahoy docker`.

This is affecting v1 and v2-alpha.

**Comment by frankcarey** [comment]
Yes, this sounds like a bug.
