### ISSUE TITLE
Add more support for Windows

### ISSUE THREAD

**Issue by frankcarey** [ahoy-cli/ahoy#48]
Right now, Windows should work but there are some things about it that are a pain.

To install for windows:

- Download the `windows-x64` build of ahoy.
- Move the file to someplace like `C:/Program Files/Ahoy/` and also rename it to `ahoy.exe`
- Update your `Path` environment variable to include that directory e.g. `C:\Program Files\Ahoy\`
- open a new cmd shell
- Since you currently need bash, you have to install that on Windows 10 anniversary edition or greater OR install cygwin which seems to work well.

Instead, some might find it useful to use powershell or something else. If we allow the init script to be changed, then we should be able to allow people to customize it to use powershell instead... something like this?

`echo {{cmd}} | powershell- Command -`

So the tasks would be:
- Support custom "entry/init" command
- Add a Windows installer that does all the tasks above for you.

**Comment by frankcarey** [comment]
Wix looks useful as a cli tool to create windows installer backed MSI files.

See https://www.codeproject.com/Tips/105638/A-quick-introduction-Create-an-MSI-installer-with for a simple example.

**Comment by r15ch13** [comment]
Ahoy has been added to [Scoop](https://github.com/lukesampson/scoop) (https://github.com/lukesampson/scoop/commit/c30c092e4a52fcd13deb98ba0c05c0987d9efdca) and can be installed with `scoop install ahoy`

**Comment by enzolutions** [comment]
@r15ch13 I tried, the install works, but ahoy itself doesn't work after couple minutes of wait I have to cancel, works for you?

**Comment by r15ch13** [comment]
This issue has to be fixed by ahoy. Calling `ahoy.exe` directly doesn't work either.

**Comment by frankcarey** [comment]
@enzolutions what happens when you call the windows version of ahoy? you say it just hangs?

**Comment by frankcarey** [comment]
Note that you can change the entrypoint if you don't have bash installed. See https://github.com/ahoy-cli/ahoy/issues/64#issuecomment-438107034 for one example.

**Comment by enzolutions** [comment]
@frankcarey just hangs, but I tested a long time ago, I will follow your recommendation as soon I have to test in windows again.

**Comment by frankcarey** [comment]
Note: this is still and issue! I'm working on it as we speak though.

**Comment by frankcarey** [comment]
OK, so it seemed to be a build issue for some reason (or perhaps I copied the wrong file).. I built it from source and it works fine. See `ahoy-bin-windows-amd64.exe` in the ahoy-2.0.0 release. 

Note that I did have issues with some of our scripts when using `cmd`, but it seemed to work fine when using `git-bash` from when you install the git client in windows. Note: If one was to use the WSL (v1 or the upcoming v2) I would think the linux build would be the one you wanted to use though.

If others could test and confirm this is working?

**Comment by schuhwerk** [comment]
Works for me (both git-bash and regular cmd)
![image](https://user-images.githubusercontent.com/865652/95588701-043b9680-0a44-11eb-8909-c455e706f9e4.png)

**Comment by weitzman** [comment]
Works for me as well.

**Comment by raiika** [comment]
For me, using cmd returns 
`An error occurred mounting one of your file systems. Please run 'dmesg' for more details.`

but using it in bash works fine.

FYI: already tried both installing ahoy via scoop nor this link (https://github.com/ahoy-cli/ahoy/releases)

**Comment by ocean** [comment]
Hi @raiika I'm one of the new maintainers of this project 👋  Thanks for your issue report.

I have a plan to test `ahoy` more in Windows soon, but at the moment we are still trying to sort out CI permission issues so we can get code merged and get some updates happening.

I had a bit of a look around for people having similar issues to you, and it seems like this error message might be to do with running multiple versions of WSL at the same time? Or maybe if you use Bitlocker but the filesystem is still locked off from WSL?

See a discussion with some possible resolutions at [this WSL issue](https://github.com/microsoft/WSL/issues/5456).

I hope this helps, if not feel free to keep this discussion open and we'll test it more on Windows in future.

**Comment by raiika** [comment]
Hi @ocean,

Thank you very much for sharing the link, I could now resolved my issue,

**Comment by ocean** [comment]
No problems @raiika , glad it works now! 👍
