### ISSUE TITLE
Better help text for `import`

### ISSUE THREAD

**Issue by frankcarey** [ahoy-cli/ahoy#59]
from @fathershawn:
Started building with ahoy.  I have this in my base file:
```ahoyapi: v2
commands:
  import: ./scripts/ahoy/robo.ahoy.yml
```
and I get this:
```ahoy -h
[fatal] yaml: unmarshal errors:
  line 4: cannot unmarshal !!str `./scrip...` into main.Command`
```
##### (Me)

We should help people moving from V1 to V2 out by providing a more clear error here than the default one.. `unmarshaling`, `!!sr` and the like are way too cryptic overall.  In the case of known v1 patterns or common patterns, we might even suggest where to find the new spec or suggest corrections.

**Comment by simesy** [comment]
I think it's `imports` now?
