### ISSUE TITLE
Ahoy only supports API version ‘v1’, but ‘v2’ given in... unable to uninstall via Linuxbrew

### ISSUE THREAD

**Issue by teranian** [ahoy-cli/ahoy#70]
Hi All,

I'm on Windows 10 WSL running Ubuntu from the app store.
Accessing terminal via Hyper.
Linuxbrew is installed and working. Kinda. 

I was originally able to install Ahoy using:

> brew install ahoy-cli/tap/ahoy

But have seen getting the error "Ahoy only supports API version ‘v1’, but ‘v2’ given in" when trying to AHOY UP on a docker image. 

I found [this issue](https://github.com/ahoy-cli/ahoy/issues/61) and tried:
> I have the same issue and this is how I fixed:
> Remove ahoy
> 
> ```
> $ brew prune ahoy
> $ brew uninstall ahoy
> ```
> After this reinstall ahoy specifying the `brew tap`
> 
> ```
> $ brew install ahoy-cli/tap/ahoy
> ```
> I don't know if the repo change his name on GitHub and something broke's

and got...

> /mnt/c/Users/elaw/projects$ brew prune
> /mnt/c/Users/elaw/projects$ 
> /mnt/c/Users/elaw/projects$ brew uninstall ahoy
> Error: No such keg: /home/linuxbrew/.linuxbrew/Cellar/ahoy

And when i try reinstalling:

> :/mnt/c/Users/elaw/projects$ brew reinstall ahoy-cli/tap/ahoy
> ==> Reinstalling ahoy-cli/tap/ahoy
> nice: cannot set niceness: Permission denied
> ==> Downloading https://github.com/ahoy-cli/ahoy/releases/download/2.0.0/ahoy-bin-darwin-amd6Already downloaded: /home/elaw/.cache/Homebrew/downloads/88e6f29cf7a638e58d73824b73be6ce0f907d40d349b16cb8e9a099980e1810e--ahoy-bin-darwin-amd64
> Error: An exception occurred within a child process:
>   ArgumentError: parent directory is world writable but not sticky
> :/mnt/c/Users/elaw/projects$

Upgrade doesn't see the install:
> :/mnt/c/Users/elaw/projects$ brew upgrade ahoy
> Error: ahoy-cli/tap/ahoy not installed
> :/mnt/c/Users/elaw/projects$

How can I remove the existing AHOY and upgrade to v2?

**Comment by ocean** [comment]
Hi @teranian I'm one of the new `ahoy` maintainers. Did you get your WSL install working eventually with a direct binary download? Or does the Linuxbrew version work now?

**Comment by teranian** [comment]
I believe I did get it working yes. I'll close this issue.
