### ISSUE TITLE
Passing arguments/flags?

### ISSUE THREAD

**Issue by kevinquillen** [ahoy-cli/ahoy#73]
Is there a way to pass arguments and flags?

I was trying to make this command:

```
  gulp:
    cmd: |
      echo "Running gulp $@"
      docker-compose run --rm node sh -c "./node_modules/gulp-cli/bin/gulp.js $@"
    usage: Runs a gulp task.
```

This is so I can run a command like:

`ahoy gulp build --flag1 --option value`

But the flags seem to be ignored.

**Comment by kevinquillen** [comment]
Also tried to do it like so after reviewing some sample commands:

```
gulp:
    cmd: "docker-compose run --rm node sh -c ./node_modules/gulp-cli/bin/gulp.js $@"
    usage: Runs a gulp task.
```

Is there any reason why `$@` is not being passed in?

When I run:

`ahoy gulp build --no-watch --env production` it does not seem to get anything after the word 'build'.

This would be akin to the command `gulp build --no-watch --env production` for me (which works), but my goal here is to not have someone need to install node/npm/gulp/etc on their host machine (local development purposes only).

**Comment by alexdesignworks** [comment]
Use `--` to separate arguments of ahoy and arguments of commands.
`ahoy gulp -- build --flag1 --option value`

You may also need to include your arguments in double quotes (this depends on how the program you are calling is parsing own arguments).

`ahoy gulp -- "build --flag1 --option value"`

**Comment by frankcarey** [comment]
Yes, the `--` is a command line thing to separate arguments and should help solve this, but I consider this an annoying bug that we should fix by requiring any ahoy specific flags come before the command, and treat any flags that come after the command as specific to the command itself.

**Comment by kevinquillen** [comment]
Closing for now - at the time I was unaware of escaping with --.
