### ISSUE TITLE
zsh: segmentation fault | on MacBook Pro 13 with Apple M1 chip

### ISSUE THREAD

**Issue by AtamDhillon** [ahoy-cli/ahoy#80]
Hi team,
Just wanted to get some help in sorting Ahoy installation on new MacBook Pro 13 with Apple M1 chip.
I ran "brew install ahoy" but got a message saying "bottle not available"
I have been able to build it from source and as per log below, it seems to have installed.
But when I run any commands, I am getting a "zsh: segmentation fault ahoy help" error and unable to run any ahoy commands.
I ran reinstall to be able to reproduce the log.

++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++
Last login: Thu Feb 11 17:52:25 on console
atamdhillon@ADPro ~ % git --version
git version 2.24.3 (Apple Git-128)
atamdhillon@ADPro ~ % brew --version
Homebrew 3.0.0
Homebrew/homebrew-core (git revision cb315; last commit 2021-02-11)
atamdhillon@ADPro ~ % brew install ahoy
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
rtl_433
==> Updated Formulae
Updated 37 formulae.

Warning: ahoy 2.0.0 is already installed and up-to-date.
To reinstall 2.0.0, run:
  brew reinstall ahoy
atamdhillon@ADPro ~ % brew reinstall ahoy
==> Downloading https://github.com/ahoy-cli/ahoy/releases/download/2.0.0/ahoy-bi
Already downloaded: /Users/atamdhillon/Library/Caches/Homebrew/downloads/88e6f29cf7a638e58d73824b73be6ce0f907d40d349b16cb8e9a099980e1810e--ahoy-bin-darwin-amd64
==> Reinstalling ahoy-cli/tap/ahoy 
==> Caveats

===== UPGRADING FROM 1.x TO 2.x =====

If you are upgrading from ahoy 1.x, note that you'll
need to upgrade your ahoyapi settings in your .ahoy.yml
files to 'v2' instead of 'v1'.

See other changes at:

https://github.com/ahoy-cli/ahoy

==> Summary
🍺  /opt/homebrew/Cellar/ahoy/2.0.0: 3 files, 3.7MB, built in 1 second
atamdhillon@ADPro ~ % ahoy help
zsh: segmentation fault  ahoy help
atamdhillon@ADPro ~ % ahoy --help
zsh: segmentation fault  ahoy --help
atamdhillon@ADPro ~ % clear

atamdhillon@ADPro ~ % brew install ahoy  
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

Warning: ahoy 2.0.0 is already installed and up-to-date.
To reinstall 2.0.0, run:
  brew reinstall ahoy
atamdhillon@ADPro ~ % brew reinstall ahoy
==> Downloading https://github.com/ahoy-cli/ahoy/releases/download/2.0.0/ahoy-bi
Already downloaded: /Users/atamdhillon/Library/Caches/Homebrew/downloads/88e6f29cf7a638e58d73824b73be6ce0f907d40d349b16cb8e9a099980e1810e--ahoy-bin-darwin-amd64
==> Reinstalling ahoy-cli/tap/ahoy 
==> Caveats

===== UPGRADING FROM 1.x TO 2.x =====

If you are upgrading from ahoy 1.x, note that you'll
need to upgrade your ahoyapi settings in your .ahoy.yml
files to 'v2' instead of 'v1'.

See other changes at:

https://github.com/ahoy-cli/ahoy

==> Summary
🍺  /opt/homebrew/Cellar/ahoy/2.0.0: 3 files, 3.7MB, built in 1 second
atamdhillon@ADPro ~ % ahoy --help
zsh: segmentation fault  ahoy --help
atamdhillon@ADPro ~ % ahoy help
zsh: segmentation fault  ahoy help
atamdhillon@ADPro ~ % ahoy h
zsh: segmentation fault  ahoy h
atamdhillon@ADPro ~ % 

++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++

**Comment by ocean** [comment]
Hi @AtamDhillon this error is because the `ahoy` binary does not currently have a version built for the Apple M1 architecture (`darwin/arm64`).

I ran into this same problem with my new Apple M1 MBP, and so I've forked this repo and created a cross-compiled version of the `ahoy` tool here https://github.com/ocean/ahoy/releases

If you download the `ahoy_darwin_arm64.tar.gz` file, open it and put the binary somewhere you can run it, things should work for you again for now.

The Homebrew version of the package won't get updated until the maintainer of this repo tags a new version of the tool.

Hope this helps you.
