### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [ahoy-cli/ahoy#81]
👋  it looks like the project does not have a formal release for quite some time.

---

relates to https://github.com/Homebrew/homebrew-core/pull/71507

**Comment by ocean** [comment]
@chenrui333 https://github.com/Homebrew/homebrew-core/pull/71507#issuecomment-789440374

**Comment by christopher-hopper** [comment]
Any update on this? 

[Apple M1 support is needed](https://github.com/ahoy-cli/ahoy/pull/82) and the [docs have broken images](https://ahoy-cli.readthedocs.io/en/latest/). these issues are fixed or awaiting review merge & release. 

I'd rather not be using a fork to get Apple M1 support, but I understand that time and effort is needed. is there anything we can do to help? 

- #82 
- #86
- Homebrew/homebrew-core#71507

**Comment by frankcarey** [comment]
Update - we have a few new maintainers that I've just added. Hope to get some PRs merged and a new release out soon

**Comment by ocean** [comment]
@christopher-hopper The Homebrew recipe for `ahoy` has been updated to include builds for ARM processors on macOS and Linux, so you should be able to use that now for your Apple M1.

An updated Homebrew version will be released sometime soon. And the image is fixed on the README, and will be fixed in the docs soon too 😄

**Comment by ocean** [comment]
Hi all, we've finally [got a new release out](https://github.com/ahoy-cli/ahoy/releases/tag/2.0.1), and it's now updated in Homebrew and Scoop too.

Thanks for your patience, and feel free to file issues with any bugs or feature requests.

And thanks to @chenrui333 for the Homebrew review and merge 👍
