### ISSUE TITLE
ahoy -f get "[fatal] Missing flag or argument."

### ISSUE THREAD

**Issue by iijiang** [ahoy-cli/ahoy#84]
I try to load a custom yml file, but any time I got this "[fatal] Missing flag or argument."

Searching the codebase, I cant find any help information for this, can someone give me a insight? 

found a similar comment here: https://github.com/ahoy-cli/ahoy/issues/78

**Comment by AlexSkrypnyk** [comment]
@iijiang 
Could you please provide the full command you are using that triggers this error.

**Comment by ocean** [comment]
@iijiang I'm going through old `ahoy` issues to clean them up, did you get this or something similar working?

**Comment by iijiang** [comment]
I am pretty sure, it has been solved for a while.

**Comment by ocean** [comment]
👍  Ok no worries, thanks @iijiang I'll close this now.
