### ISSUE TITLE
Offering help with project maintenance

### ISSUE THREAD

**Issue by AlexSkrypnyk** [ahoy-cli/ahoy#88]
Hi Frank

AhoyCLI got a lot of popularity in Drupal community lately.

I would like to help to get the project moving with PRs and issues.

I also know several community members who would want to contribute to the process. Maybe people can nominate themselves in this issue.

Could you please at least let us know if you can consider this help.

Thank you

**Comment by ocean** [comment]
Hi @AlexSkrypnyk - see #89 - I've been added, if you're interested @frankcarey could add you as well 👍
