### ISSUE TITLE
Delegating Maintenance to Contributors

### ISSUE THREAD

**Issue by frankcarey** [ahoy-cli/ahoy#89]
Hello AhoyCli community!

First, thank you for using Ahoy and to all the folks that have helped turn a weekend project that scratched my own itch into a project that continues to grow it's userbase around the world. Growing despite my absence these last few years. I had moved on from DevOps to work for Vimeo for a few years, and then I've been at Game Company Fable Studio for the last 3 years, so unfortunately Ahoy has gotten precious little attention from me for like 5+ years, but the community of developers continued to use it and update it as the world of Golang progressed as well. This is non atypical in opensource, but I do apologize for not including more of you that have volunteered to support the project sooner.

Better late than never, I've recently invited 2 new maintainers to the project:
* @acouch [Aaron Couch] : A friend and past colleague of mine on the open source DKAN project, which sponsored Ahoy's original development as part of our work for the US Health and Human Services.
*  @ocean [Drew Robinson]: Another Drupalist from Australia and who's contributed (and helpfully pinged me to make this happen finally).
* @AlexSkrypnyk: A Drupalist and DevOps developer also from Australia.

My understanding is that Ahoy has mostly been used in relation to various Drupal projects, but my hope is that many types of projects can take advantage of a simpler way to create their own project specific scripts and avoid having to keep documentation or text files with lines they copy and paste. I still find needs for this in my own projects, but now that I'm typically working in Windows (never expected that to happen), I'll hopefully be able to contribute to make that environment work as well.

Again, thank you to everyone who has contributed and found this project useful. I'm still working in github daily, but ping me at frankcarey on twitter if you need to reach me.

**Comment by ocean** [comment]
Thanks for adding me @frankcarey ! And welcome @acouch 

I'll start by saying that I don't have a huge amount of time to dedicate to the project either (full time work, family, etc, similar stories for lots of people I know), but I will endeavour to review and merge reasonable PRs as they come in.

Hopefully we can also get an updated Homebrew release out soon with Apple M1 support.

**Comment by ocean** [comment]
@frankcarey @AlexSkrypnyk has offered his help too, he is another Australia-based Drupalist who rewrote the `pygmy` Docker toolset in Go, which is another tool that we use on multiple Drupal projects along with `ahoy`.

**Comment by AlexSkrypnyk** [comment]
Hey guys! Thank you for adding me here @frankcarey 

I'm really interested in moving the project forward, with a priority on resolving currently opened issues and PRs.

@acouch @ocean @frankcarey 
What is the process and procedure to create new releases:
1. How often should we be creating new releases?
2. Who is responsible for creating them?

**Comment by acouch** [comment]
Thanks for creating the issue. I look forward to digging in as I have a little more time this summer. @AlexSkrypnyk 

I think your questions are up to us. Do you want to find a slack channel to chat in or have a short zoom? I would say that I won't have time to do regular periodic releases, so think it would make sense to just release when we have updates. I think we could all be responsible for pushing releases. It would maybe make sense to have a rule to at least have another one of the maintainers review any PRs. I don't have a lot of opinions on the features or roadmap of this tool, just want to keep it as light-weight and focused as possible.

**Comment by frankcarey** [comment]
Thanks All - God speed!

**Comment by ocean** [comment]
Ok @acouch @AlexSkrypnyk are we ready to make a new release? Want to discuss somewhere? (for ease I was thinking we could create a channel on the Drupal Slack maybe?)

**Comment by ocean** [comment]
Ok, a new release `2.0.1` is out and has been sent to homebrew as well 👍
