### ISSUE TITLE
Get Automated tests working again

### ISSUE THREAD

**Issue by frankcarey** [ahoy-cli/ahoy#90]
We were using CircleCI, with BATS tests, but it seems to no longer be active. I'll try to take a look and see what happened and if we can easily get it back up and running.

**Comment by AlexSkrypnyk** [comment]
@frankcarey @ocean 
CircleCI needs a project owner to login and re-link the project with GitHub by "following it". 
The tests are working good - we just need to switch the CI back on.

I'm happy to take on the CI maintenance for this project since I work with CircleCI daily.

**Comment by AlexSkrypnyk** [comment]
https://app.circleci.com/settings/project/github/ahoy-cli/ahoy?utm_campaign=locked_project&utm_content=project_dashboard_tooltip&utm_medium=copy_admin_project_set_up_link&utm_source=circleci_onboarding

**Comment by ocean** [comment]
Hi @frankcarey - we currently can't progress any code updates at all until CircleCI is reconnected and working again (see above and #93 ).

Can you please click the link above to re-enable it? Or give one of us permissions on the project to do so? Perhaps the new maintainer group should be added to the `ahoy-cli` GH organisation?

**Comment by ocean** [comment]
Just so you know @AlexSkrypnyk , I've messaged @frankcarey [on Twitter](https://twitter.com/drew_was_ocean/status/1531083936855494657) a [couple of times](https://twitter.com/drew_was_ocean/status/1533368055937454081) now, still waiting for him to get onto clicking this link to reconnect CircleCI.

CircleCI favourited one of my tweets mentioning them, so I [sent them a message](https://twitter.com/drew_was_ocean/status/1534339296848556032) too to see if they could help, I doubt it though.

**Comment by frankcarey** [comment]
I think this is done now finally - sorry for the delay. Feel free to keep up the public shaming if I don't respond, it works! 😜

**Comment by ocean** [comment]
Thanks @frankcarey ! Hopefully we don't have to bug you too much again now 😄

**Comment by frankcarey** [comment]
Thanks!
